name: mock_web_server
version: 5.0.0-nullsafety.1
description: Versatile scriptable Web Server for real integration tests in Flutter, server, and Dart CLI applications
homepage: https://git.starcarr.co/Dart/MockWebServer

dev_dependencies:
  test: 1.19.2
  lint: 1.7.2

environment:
  sdk: ">=2.14.0 <3.0.0"
